# Sprite scaling factors
PLAYER_SCALING = 1.2
ALIEN_SCALING = 1
# Window dimensions and title
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_TITLE = "Alien Invasion - Python Arcade"
# Player configuration
PLAYER_LIVES = 3
LIVES_ICON_SCALING = 0.95
MOVEMENT_SPEED = 200
BULLET_SPEED = 300
SHOOT_COOLDOWN = 0.2  # 0.2 seconds
# Alien fleet configuration
ALIEN_ROWS = 5
ALIEN_COLUMNS = 11
TOP_ALIEN_ROWS = 2
MID_ALIEN_ROWS = 2
BOTTOM_ALIEN_ROWS = 1
ALIEN_X_SPACING = 50
ALIEN_Y_SPACING = 50
ALIEN_START_X = 100
ALIEN_START_Y = WINDOW_HEIGHT - 70
ALIEN_SPEED = 50
ALIEN_DROP = 35
ALIEN_BULLET_SPEED = 200
ALIEN_SHOOT_COOLDOWN = 2.0  # 2 seconds
MIN_COOLDOWN = 1.5 # Minimum cooldown for alien shooting
MAX_FLEET_SPEED = 85  # Max speed for alien fleet 